Bump requirements to solve out-dated molecule dep
As a side-note, I couldn't get the `--generate-hashes` flag to work with
`pip-compile` without crashing with the error:

```
  File
  "/home/mike/.virtualenvs/pip-tools/local/lib/python2.7/site-packages/piptools/repositories/pypi.py",
  line 169, in get_hashes
      matching_candidates = candidates_by_version[matching_versions[0]]
      IndexError: list index out of range

```

Since these reqs are really for CI and occasionally local testing and
not for prod - I'm going to just push forward to get things working.